FROM ghcr.io/n8n-io/n8n:1.120.0

ENV NODE_OPTIONS=--max-old-space-size=350
ENV N8N_RUNNERS_ENABLED=false
ENV N8N_AI_ENABLED=false
ENV N8N_CONCURRENCY_PRODUCTION_LIMIT=1
ENV N8N_PROXY_HOPS=1
ENV EXECUTIONS_MODE=regular
ENV DB_LOGGING_ENABLED=false
ENV N8N_PAYLOAD_SIZE_MAX=16777216
